# Generated by Django 5.2 on 2026-01-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_dailyactivity_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learninggoal',
            name='ai_solution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='learninggoal',
            name='is_satisfied',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learninggoal',
            name='satisfaction_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='learninggoal',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('learning', 'Learning'), ('completed', 'Completed')], default='planned', max_length=15),
        ),
        migrations.AddField(
            model_name='learninggoal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
