# Generated by Django 6.0.1 on 2026-01-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_learninggoal_ai_solution_learninggoal_is_satisfied_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learninggoal',
            name='ai_solution',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('video', 'YouTube / Video'), ('article', 'Article / Blog'), ('course', 'Course'), ('book', 'Book'), ('docs', 'Documentation'), ('notes', 'Notes')], max_length=12),
        ),
    ]
