# Generated by Django 5.2 on 2026-01-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_learninggoal_ai_solution_alter_resource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='short_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(max_length=30),
        ),
    ]
