# Generated by Django 5.2 on 2026-01-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_resource_short_description_alter_resource_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('video', 'YouTube / Video'), ('article', 'Article / Blog'), ('course', 'Course'), ('book', 'Book / PDF'), ('docs', 'Documentation'), ('notes', 'Notes'), ('practice', 'Practice Platform')], max_length=15),
        ),
    ]
