# Generated by Django 5.2 on 2026-01-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_task_task_type_alter_task_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ai_solution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='custom_subject',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='task',
            name='material',
            field=models.FileField(blank=True, null=True, upload_to='tasks/'),
        ),
        migrations.AddField(
            model_name='task',
            name='needs_help',
            field=models.BooleanField(default=False),
        ),
    ]
