# Generated by Django 5.2 on 2026-01-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_task_ai_solution_task_custom_subject_task_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('assignment', 'Assignment'), ('practice', 'Practice'), ('revision', 'Revision'), ('project', 'Project'), ('reading', 'Reading'), ('exam', 'Exam Prep'), ('other', 'Other')], default='assignment', max_length=20),
        ),
    ]
