# Generated by Django 5.2 on 2026-01-24 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_task_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learninggoal',
            name='ai_solution',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('assignment', 'Assignment'), ('study', 'Study'), ('revision', 'Revision'), ('project', 'Project'), ('exam', 'Exam Prep'), ('reading', 'Reading'), ('other', 'Other')], default='study', max_length=20),
        ),
        migrations.CreateModel(
            name='TaskMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('ai', 'AI')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.task')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
