# Generated by Django 6.0.1 on 2026-01-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_userstats_codeforces_solved_userstats_codeforces_xp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='github_xp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
