# Generated by Django 6.0.1 on 2026-01-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_userstats_github_xp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstats',
            name='codeforces_solved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='codeforces_xp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='gfg_solved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='gfg_xp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='hackerrank_solved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='hackerrank_xp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='leetcode_solved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='leetcode_xp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
