# Generated by Django 6.0.1 on 2026-01-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_learninggoal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='github_repos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
