# Generated by Django 5.2 on 2026-02-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_userstats_github_repos'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='leetcode_easy',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='leetcode_hard',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='leetcode_medium',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
