# Generated by Django 5.2 on 2026-02-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_dailyactivity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='total_commits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
