# Generated by Django 5.2 on 2026-05-26 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_userstats_leetcode_easy_userstats_leetcode_hard_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyactivity',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='leaderboardentry',
            options={'ordering': ['rank']},
        ),
        migrations.RemoveField(
            model_name='note',
            name='topic',
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='base_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='platformaccount',
            name='profile_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='core.learninggoal'),
        ),
        migrations.AddField(
            model_name='task',
            name='ai_solution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='needs_help',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='core.subject'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.topic'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyactivity',
            unique_together={('account', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='platformaccount',
            unique_together={('user', 'platform')},
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'completed'], name='core_task_user_id_02509f_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'deadline'], name='core_task_user_id_c0b95c_idx'),
        ),
    ]
