# Generated by Codex on 2026-05-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_alter_dailyactivity_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userstats",
            name="codechef_username",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="userstats",
            name="codechef_solved",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userstats",
            name="codechef_rating",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userstats",
            name="codechef_contests",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userstats",
            name="codechef_xp",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
